[package]
name = "egui-image-example"
version = "0.1.0"
edition = "2021"
description = "Really simple example of using egui with an image"

[dependencies]
eframe = "0.19.0"
egui_extras = { version = "0.19.0", features = ["image"] }
image = { version = "0.24", features = ["jpeg", "png"] }